# Generated by Django 4.0.2 on 2022-09-18 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_staff_c_address_staff_covenant_staff_cv_and_more'),
        ('users', '0003_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.JSONField(choices=[('ICT1', 'ICT1'), ('ICT2', 'ICT2'), ('ICT3', 'ICT3'), ('FO', 'Faculty Officer'), ('EO', 'Exam officer'), ('LA', 'Level Adviser'), ('LEC', 'Lecturer')], default=dict),
        ),
    ]
