# Generated by Django 4.0.2 on 2022-09-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_staff_user_department_user_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.JSONField(default=dict),
        ),
    ]
