# Generated by Django 4.1.3 on 2022-12-04 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_staff_answer_alter_staff_email_and_more'),
        ('users', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='semester_session_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='base.setting'),
            preserve_default=False,
        ),
    ]
