# Generated by Django 4.1.3 on 2022-12-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
