# Generated by Django 4.1.3 on 2022-12-12 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_setting_semester_open_close'),
        ('users', '0008_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='logUserRoleForSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.JSONField()),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('role_status', models.CharField(default='PENDING', max_length=15)),
                ('deleted', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_semester_role_related', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_role_related', to=settings.AUTH_USER_MODEL)),
                ('semester_session', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.setting')),
            ],
        ),
    ]
