# Generated by Django 4.1.3 on 2022-12-12 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_setting_semester_open_close'),
        ('users', '0009_loguserroleforsemester'),
    ]

    operations = [
        migrations.AddField(
            model_name='loguserroleforsemester',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.department'),
        ),
        migrations.AddField(
            model_name='loguserroleforsemester',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.programme'),
        ),
        migrations.AlterField(
            model_name='loguserroleforsemester',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_by_semester_role_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
