# Generated by Django 4.1.3 on 2022-12-12 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_setting_semester_open_close'),
        ('users', '0010_loguserroleforsemester_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loguserroleforsemester',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.department'),
        ),
        migrations.AlterField(
            model_name='loguserroleforsemester',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.programme'),
        ),
    ]
