# Generated by Django 4.1.3 on 2022-12-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_loguserroleforsemester_department_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loguserroleforsemester',
            table='semester_user_roles_log',
        ),
    ]
