# Generated by Django 4.1.3 on 2022-12-27 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0002_alter_curriculum_program_alter_curriculum_semester'),
        ('users', '0015_alter_loguserroleforsemester_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loguserroleforsemester',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='department_semester_role_related', to='undergraduate.department'),
        ),
        migrations.AlterField(
            model_name='loguserroleforsemester',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='programme_semester_role_related', to='undergraduate.programme'),
        ),
    ]
