# Generated by Django 4.1.3 on 2022-12-30 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_loguserroleforsemester_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loguserroleforsemester',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_semester_role_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
