# Generated by Django 4.1.3 on 2023-01-20 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_staff_user'),
        ('users', '0019_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='semester_session_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.setting'),
        ),
    ]
