# Generated by Django 4.1.3 on 2023-01-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_staff_user'),
        ('users', '0020_alter_user_semester_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='semester_session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.setting'),
        ),
    ]
