# Generated by Django 4.1.3 on 2023-02-10 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_semester_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loguserroleforsemester',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_semester_role_related', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
