# Generated by Django 4.1.3 on 2023-03-16 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0024_student_id_alter_registration_matric_number_fk_and_more'),
        ('users', '0024_alter_user_department_alter_user_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='department_user_related', to='undergraduate.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='programme_user_related', to='undergraduate.programme'),
        ),
    ]
