# Generated by Django 4.1.3 on 2023-03-16 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0024_student_id_alter_registration_matric_number_fk_and_more'),
        ('users', '0025_alter_user_department_alter_user_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='faculty_user_related', to='undergraduate.faculty'),
        ),
    ]
