# Generated by Django 4.1.3 on 2023-03-19 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0027_programme_programme_id_alter_curriculum_programme_and_more'),
        ('users', '0029_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveladviser',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='undergraduate.programme', to_field='programme_id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='department_user_related', to='undergraduate.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='programme_user_related', to='undergraduate.programme', to_field='programme_id'),
        ),
    ]
