# Generated by Django 4.1.3 on 2023-03-19 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0027_programme_programme_id_alter_curriculum_programme_and_more'),
        ('users', '0030_alter_leveladviser_programme_alter_user_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loguserroleforsemester',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='department_semester_role_related', to='undergraduate.department'),
        ),
        migrations.AlterField(
            model_name='loguserroleforsemester',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='programme_semester_role_related', to='undergraduate.programme', to_field='programme_id'),
        ),
    ]
