# Generated by Django 4.1.3 on 2023-03-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_user_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveladviser',
            name='programme',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='loguserroleforsemester',
            name='programme',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
