# Generated by Django 4.1.3 on 2023-03-20 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0037_alter_curriculum_programme_and_more'),
        ('users', '0035_alter_leveladviser_programme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loguserroleforsemester',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='programme_semester_role_related', to='undergraduate.programme'),
        ),
    ]
