# Generated by Django 4.1.3 on 2023-03-20 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0038_alter_curriculum_programme_and_more'),
        ('users', '0036_alter_loguserroleforsemester_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveladviser',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='undergraduate.programme'),
        ),
        migrations.AlterField(
            model_name='user',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='programme_user_related', to='undergraduate.programme'),
        ),
    ]
