# Generated by Django 4.1.3 on 2023-03-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_user_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='programme',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
