# Generated by Django 4.1.3 on 2023-03-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_leveladviser_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loguserroleforsemester',
            name='programme',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
