# Generated by Django 4.1.3 on 2023-03-21 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0040_alter_curriculum_programme_and_more'),
        ('users', '0043_alter_leveladviser_programme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='programme_user_related', to='undergraduate.programme', to_field='programme_code'),
        ),
    ]
