# Generated by Django 4.1.3 on 2023-01-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0004_lecturercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='deleted',
            field=models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='registration',
            name='matric_number',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='registration',
            name='unit_id',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_code', 'unit_id')},
        ),
    ]
