# Generated by Django 4.1.3 on 2023-01-10 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0004_lecturercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='deleted',
            field=models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='registration',
            name='matric_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='undergraduate.student', to_field='matric_number'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='unit_id',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_code', 'unit_id')},
        ),
    ]
