# Generated by Django 4.1.3 on 2023-01-10 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0008_alter_registration_matric_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stud_matric_number',
            new_name='matric_number',
        ),
        migrations.AlterField(
            model_name='registration',
            name='matric_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ug_reg_stud_related', to='undergraduate.student', to_field='stud_matric_number'),
        ),
    ]
