# Generated by Django 4.1.3 on 2023-01-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0010_alter_registration_matric_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='matric_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ug_reg_stud_related', to='undergraduate.student'),
        ),
    ]
