# Generated by Django 4.0.2 on 2022-03-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=45)),
                ('course_description', models.CharField(blank=True, max_length=191, null=True)),
                ('course_id_of_equivalence', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=45, null=True)),
                ('last_update_date', models.CharField(blank=True, max_length=45, null=True)),
                ('course_level', models.CharField(blank=True, max_length=10, null=True)),
                ('register_flag', models.CharField(blank=True, max_length=10, null=True)),
                ('deleted', models.CharField(blank=True, max_length=1, null=True)),
                ('unit_id', models.CharField(blank=True, max_length=45, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
