# Generated by Django 4.0.2 on 2022-03-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id_of_equivalence',
            field=models.CharField(max_length=45),
        ),
    ]
