# Generated by Django 4.0.2 on 2022-03-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_course_id_of_equivalence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id_of_equivalence',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
