# Generated by Django 4.0.2 on 2022-03-03 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_curriculum_course_level_and_more'),
        ('course', '0004_lecturercourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturercourse',
            name='settings',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='base.setting'),
            preserve_default=False,
        ),
    ]
