# Generated by Django 4.0.2 on 2022-03-03 17:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_curriculum_course_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0005_lecturercourse_settings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lecturercourse',
            unique_together={('course', 'lecturer', 'settings')},
        ),
    ]
