# Generated by Django 4.0.2 on 2022-03-03 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0006_alter_lecturercourse_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturercourse',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
