# Generated by Django 4.0.2 on 2022-03-05 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_lecturercourse_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturercourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='courses', to='course.course'),
        ),
    ]
