# Generated by Django 4.0.2 on 2022-09-10 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0008_alter_lecturercourse_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturercourse',
            old_name='time_approved',
            new_name='approved_at',
        ),
        migrations.AddField(
            model_name='lecturercourse',
            name='approval_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturercourse',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='LecturerCourse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lecturercourse',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
