# Generated by Django 4.1.3 on 2022-12-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_rename_time_approved_lecturercourse_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturercourse',
            name='status',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
