# Generated by Django 4.1.3 on 2022-12-15 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ug_curriculum_program_related', to='undergraduate.programme'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='semester',
            field=models.CharField(choices=[('1', 'FIRST SEMESTER'), ('2', 'SECOND_SEMESTER')], default='1', max_length=1),
        ),
    ]
