# Generated by Django 4.1.3 on 2022-12-31 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_setting_semester_open_close'),
        ('undergraduate', '0003_rename_program_curriculum_programme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=45)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED')], default='PENDING', max_length=15)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approval_details', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='LecCourse_approved_by_rn', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='LecCourse_lecturer_rn', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='LecCourse_settings_rn', to='base.setting')),
            ],
            options={
                'db_table': 'ug_lecturers_courses',
                'unique_together': {('course_code', 'lecturer', 'settings')},
            },
        ),
    ]
