# Generated by Django 4.1.3 on 2023-01-11 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0005_alter_registration_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
