# Generated by Django 4.1.3 on 2023-01-11 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('undergraduate', '0006_delete_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=30)),
                ('session_id', models.CharField(max_length=30)),
                ('course_code', models.CharField(max_length=30)),
                ('Lecturer_id', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(max_length=5)),
                ('score', models.IntegerField()),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
                ('last_updated_date_old', models.CharField(blank=True, max_length=30, null=True)),
                ('last_updated_by_old', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='N', max_length=1)),
                ('satisfied', models.CharField(blank=True, max_length=5, null=True)),
                ('unit_id', models.CharField(max_length=45)),
                ('app_user_id', models.CharField(blank=True, max_length=191, null=True)),
                ('level', models.CharField(blank=True, max_length=5, null=True)),
                ('record_status', models.CharField(blank=True, default='OFF', max_length=5, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('last_updated_by_new', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ug_registration_user_related', to=settings.AUTH_USER_MODEL)),
                ('matric_number_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ug_reg_stud_related', to='undergraduate.student', to_field='matric_number')),
            ],
            options={
                'db_table': 'ug_registration',
                'unique_together': {('matric_number_fk', 'semester', 'session_id', 'course_code')},
            },
        ),
    ]
