# Generated by Django 4.1.3 on 2023-01-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0007_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='unit',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
