# Generated by Django 4.1.3 on 2023-01-12 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('undergraduate', '0011_alter_course_last_updated_by_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='last_updated_by_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ug_course_user_related', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
