# Generated by Django 4.1.3 on 2023-02-02 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0013_alter_faculty_last_updated_by_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regsummary',
            name='matric_number',
        ),
        migrations.AddField(
            model_name='regsummary',
            name='matric_number_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ug_reg_sum_related', to='undergraduate.student', to_field='matric_number'),
        ),
    ]
