# Generated by Django 4.1.3 on 2023-02-15 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0014_remove_regsummary_matric_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturercourse',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='undergraduate.programme'),
        ),
    ]
