# Generated by Django 4.1.3 on 2023-02-15 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0015_lecturercourse_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturercourse',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='undergraduate.programme'),
        ),
    ]
