# Generated by Django 4.1.3 on 2023-02-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0018_alter_lecturercourse_dpt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturercourse',
            old_name='dpt',
            new_name='department',
        ),
    ]
