# Generated by Django 4.1.3 on 2023-02-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0021_remove_student_id_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='student',
        #     name='matric_number',
        #     field=models.CharField(max_length=50, primary_key=True, serialize=False),
        # ),
    ]
