# Generated by Django 4.1.3 on 2023-02-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0022_alter_student_matric_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='matric_number_fk',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='regsummary',
            name='matric_number_fk',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
