# Generated by Django 4.1.3 on 2023-03-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0024_student_id_alter_registration_matric_number_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='programme_id',
        ),
        migrations.AddField(
            model_name='programme',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
