# Generated by Django 4.1.3 on 2023-03-19 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0026_alter_lecturercourse_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='programme_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ug_curriculum_program_related', to='undergraduate.programme', to_field='programme_id'),
        ),
        migrations.AlterField(
            model_name='lecturercourse',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='undergraduate.department'),
        ),
        migrations.AlterField(
            model_name='lecturercourse',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='undergraduate.programme', to_field='programme_id'),
        ),
    ]
