# Generated by Django 4.1.3 on 2023-03-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0029_rename_programme_id_programme_programme_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='programme_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
