# Generated by Django 4.1.3 on 2023-03-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0030_alter_programme_programme_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='created',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='department',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='required_ctcup',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='required_cteup',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='updated',
        ),
    ]
