# Generated by Django 4.1.3 on 2023-03-20 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0031_remove_programme_created_remove_programme_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='undergraduate.department'),
        ),
    ]
