# Generated by Django 4.1.3 on 2023-03-20 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0032_programme_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='undergraduate.department'),
        ),
    ]
