# Generated by Django 4.1.3 on 2023-03-20 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('undergraduate', '0033_alter_programme_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='department',
        ),
        migrations.AddField(
            model_name='programme',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='deleted',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ug_programme_user_related', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
        migrations.AddField(
            model_name='programme',
            name='required_ctcup',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='required_cteup',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
