# Generated by Django 4.1.3 on 2023-03-20 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0035_programme_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='deleted',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='undergraduate.department'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
