# Generated by Django 4.1.3 on 2023-03-20 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0037_alter_curriculum_programme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ug_curriculum_program_related', to='undergraduate.programme'),
        ),
        migrations.AlterField(
            model_name='lecturercourse',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='undergraduate.programme'),
        ),
    ]
