# Generated by Django 4.1.3 on 2023-03-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0042_student_id_alter_registration_matric_number_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matric_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
