# Generated by Django 4.1.3 on 2023-03-26 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate', '0053_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='matric_number_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ug_reg_stud_related', to='undergraduate.student', to_field='matric_number'),
        ),
        migrations.AddField(
            model_name='regsummary',
            name='matric_number_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ug_reg_sum_related', to='undergraduate.student', to_field='matric_number'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('matric_number_fk', 'semester', 'session_id', 'course_code')},
        ),
        migrations.AlterUniqueTogether(
            name='regsummary',
            unique_together={('matric_number_fk', 'semester', 'session_id')},
        ),
    ]
