# Generated by Django 4.0.2 on 2022-03-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_number', models.CharField(max_length=50, unique=True)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('lga', models.CharField(blank=True, max_length=191, null=True)),
                ('current_level', models.CharField(blank=True, max_length=5, null=True)),
                ('state_origin', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('programme', models.CharField(blank=True, max_length=191, null=True)),
                ('city_resident', models.CharField(blank=True, max_length=100, null=True)),
                ('state_resident', models.CharField(blank=True, max_length=100, null=True)),
                ('matric_date', models.CharField(blank=True, max_length=50, null=True)),
                ('graduation_date', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('last_update_date', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('ctcp', models.IntegerField(blank=True, null=True)),
                ('ctnur', models.IntegerField(blank=True, null=True)),
                ('ctnup', models.IntegerField(blank=True, null=True)),
                ('ctnuf', models.IntegerField(blank=True, null=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('email1', models.CharField(blank=True, max_length=100, null=True)),
                ('email2', models.CharField(blank=True, max_length=100, null=True)),
                ('student_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('prog_code', models.CharField(blank=True, max_length=50, null=True)),
                ('picture', models.CharField(blank=True, max_length=191, null=True)),
                ('ctcup', models.IntegerField(blank=True, null=True)),
                ('cteup', models.IntegerField(blank=True, null=True)),
                ('notify_sms', models.CharField(blank=True, max_length=1, null=True)),
                ('notify_email', models.CharField(blank=True, max_length=1, null=True)),
                ('parent_pwd', models.CharField(blank=True, max_length=191, null=True)),
                ('registration_pwd', models.CharField(blank=True, max_length=191, null=True)),
                ('financial_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('notify_bursary_sms', models.CharField(blank=True, max_length=1, null=True)),
                ('jamb_reg', models.CharField(blank=True, max_length=50, null=True)),
                ('run_mail', models.CharField(blank=True, max_length=100, null=True)),
                ('degree_sought', models.CharField(blank=True, max_length=100, null=True)),
                ('acad_status', models.CharField(blank=True, max_length=50, null=True)),
                ('entry_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('hold_record', models.CharField(blank=True, max_length=1, null=True)),
                ('run_mail_2', models.CharField(blank=True, max_length=191, null=True)),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
