# Generated by Django 4.0.2 on 2022-03-02 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=50)),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'faculties',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=50)),
                ('semester_name', models.CharField(max_length=50)),
                ('semester_code', models.IntegerField()),
                ('status', models.CharField(blank=True, default='NONE', max_length=15, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=11)),
                ('password', models.TextField()),
                ('profile_image', models.TextField()),
                ('profile_image_small', models.TextField()),
                ('staff_type', models.CharField(max_length=10)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('online', models.IntegerField()),
                ('activate', models.IntegerField()),
                ('pwdreset', models.IntegerField()),
                ('lastupdate', models.CharField(max_length=255)),
                ('form_completed', models.IntegerField()),
                ('retired', models.IntegerField()),
                ('adjunct', models.IntegerField()),
                ('disengaged', models.IntegerField()),
                ('reason', models.TextField()),
                ('r_date', models.CharField(max_length=255)),
                ('support_team', models.IntegerField()),
                ('research_output', models.IntegerField()),
                ('phd_output', models.IntegerField()),
                ('msc_output', models.IntegerField()),
                ('date', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('myprofile', models.TextField(blank=True, null=True)),
                ('staff_no', models.CharField(blank=True, max_length=255, null=True)),
                ('sh_staff_no', models.CharField(blank=True, max_length=255, null=True)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('middlename', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('former_firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('former_middlename', models.CharField(blank=True, max_length=255, null=True)),
                ('former_lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('mstatus', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('state_origin', models.CharField(blank=True, max_length=255, null=True)),
                ('istate', models.CharField(blank=True, max_length=255, null=True)),
                ('ipbirth', models.CharField(blank=True, max_length=255, null=True)),
                ('date_app_uni', models.CharField(blank=True, max_length=255, null=True)),
                ('date_app_pubservice', models.CharField(blank=True, max_length=255, null=True)),
                ('p_address', models.TextField(blank=True, null=True)),
                ('c_address', models.TextField(blank=True, null=True)),
                ('r_address', models.TextField(blank=True, null=True)),
                ('p_email', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('landline', models.CharField(blank=True, max_length=255, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('intercom', models.CharField(blank=True, max_length=255, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('pob', models.CharField(blank=True, max_length=255, null=True)),
                ('poblga', models.CharField(blank=True, max_length=255, null=True)),
                ('health', models.CharField(blank=True, max_length=255, null=True)),
                ('cv', models.CharField(blank=True, max_length=255, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('form_completed', models.CharField(blank=True, max_length=255, null=True)),
                ('email_status', models.IntegerField(blank=True, null=True)),
                ('covenant', models.IntegerField(blank=True, null=True)),
                ('leave_app', models.IntegerField(blank=True, null=True)),
                ('retired', models.IntegerField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.staff', to_field='userid')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('programme_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('programme', models.CharField(max_length=50)),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.department')),
            ],
            options={
                'db_table': 'programmes',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.faculty'),
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_level', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('semester', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('last_update_date', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('register_flag', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.programme')),
            ],
            options={
                'db_table': 'curriculum',
            },
        ),
    ]
