# Generated by Django 4.0.2 on 2022-03-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='course_level',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='last_update_date',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='register_flag',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='course_reg_level',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='semester',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
