# Generated by Django 4.0.2 on 2022-09-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_curriculum_course_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='semester_code',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2')]),
        ),
        migrations.AlterField(
            model_name='setting',
            name='semester_name',
            field=models.CharField(choices=[('FIRST SEMESTER', 'FIRST SEMESTER'), ('SECOND SEMESTER', 'SECOND SEMESTER')], max_length=50),
        ),
        migrations.AlterField(
            model_name='setting',
            name='status',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('ACTIVE', 'ACTIVE')], default='NONE', max_length=15, null=True),
        ),
    ]
