# Generated by Django 4.0.2 on 2022-09-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_setting_semester_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='session',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterUniqueTogether(
            name='setting',
            unique_together={('session', 'semester_name', 'semester_code')},
        ),
    ]
