# Generated by Django 4.1.3 on 2022-12-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_staff_answer_alter_staff_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='semester_open_close',
            field=models.BooleanField(default=False),
        ),
    ]
